### PR TITLE
Query entities by Id

### PR DESCRIPTION
**Pull request by juanferrer**
Expose `EntityId` through `Entity.Id`.
Add `Where()` to `EntityQueryBuilder`, which accepts a predicate to filter entities by Id (can be expanded).
Add tests for `Where()`.

### CODE REVIEW

**Comment by Doraku** [comment]
why would you need access to the actual entity id? This is just an implementation detail and this id has no bearing on what an entity is, they are even reused when disposing entities. Just wondering what you would achieve with this.

**Comment by juanferrer** [comment]
Well, it's not really the ID itself I'm interested in, rather the ability to keep a reference to different entities and query them outside of a system. I thought a simple way would be to store the IDs and then query the world for the specific entities.

If you can think of a better way to query specific entities, I'll happy look into that. Or maybe even a way to "update" the reference to a specific entity.

**Comment by Doraku** [comment]
you can use a component as key and access specific entities via [EntityMap](https://github.com/Doraku/DefaultEcs#asmap), those containers track changes and will be updated as you create/dispose/add component/remove component, maybe that's more what you are looking for?

**Comment by juanferrer** [comment]
Yeah, your suggestion works and performs better. Closing.

**Pull request closed without merging**
