### PR TITLE
#66 initial fix

### PR DESCRIPTION
**Pull request by MarkWilds**
Dont know if this is the way you want it @Doraku.
But it works when tested.

### CODE REVIEW

**Comment by Doraku** [comment]
I would have probably done it the same, entities are enumerated twice but this is just the initialization so performance is not as critical.
Could you add a corresponding test in the AManagedResourceTest? You can probably duplicate the one checking for the array variant and reverse the Manage/CreateEntity steps.
Also can you add "fixed AResourceManager.Manage for existing entities" in the description part of DefaultEcs.Release.csproj?
Just wondering what is this `.idea` you added to gitignore.
Sorry for all this, I am at work and can't do much on the phone ^^"

**Comment by MarkWilds** [comment]
Dont have to apologize haha, I like this project and want to invest.
The .idea is a folder created by my IDE(rider).

I will look into creating the test, I did not manage to get the test project to work as my solution was trying to load the projects in an infinite loop. (something with wanting to use the VS MSbuild as I am solely on core currently)

**Comment by Doraku** [comment]
Maybe if you comment out the net452 and net48 targets of the defaultecs.test.csproj it should be able to load? (obviously don't commit this :D)
That makes me think I should look into setting up a github action to validate pullrequest.

**Comment by MarkWilds** [comment]
removing the targets worked.

**Pull request merged**
